version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: network:frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./application
      dockerfile: Dockerfile
    ports:
      - "8085:8085"

  authserver:
    build:
      context: ./authserver
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  resourceserver:
    build:
      context: ./resourceserver
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
